# Generated by Django 2.1.5 on 2022-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20220712_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_contact_linkdin_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
