# Generated by Django 2.1.5 on 2021-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_jobs',
            field=models.ManyToManyField(blank=True, to='jobs.JobPost'),
        ),
    ]
