# Generated by Django 2.1.5 on 2021-04-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
