"""
Django settings for fastforward project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

import django_heroku
import psycopg2.extensions
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9^^j@!!lnss*=7id_1cl)8)ka+e^@0&hi0=4fdo89(vy6cf99m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'django.contrib.humanize',
    'social_django'
]

CUSTOM_APPS = ['User', 'jobs']

INSTALLED_APPS += CUSTOM_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware'
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.linkedin.LinkedinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'fastforward.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'jobs.context_processor.filter_processor.location_list',
                'jobs.context_processor.filter_processor.job_title_filter',
            ],
        },
    },
]

WSGI_APPLICATION = 'fastforward.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3Old'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

TIME_INPUT_FORMATS = [
    '%I:%M:%S %p',  # 6:22:44 PM
    '%I:%M %p',  # 6:22 PM
    '%I %p',  # 6 PM
    '%H:%M:%S',     # '14:30:59'
    '%H:%M:%S.%f',  # '14:30:59.000200'
    '%H:%M',        # '14:30'
]

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

LOGOUT_REDIRECT_URL = 'index'
LOGIN_REDIRECT_URL = 'index'

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '865k9pfera6rkn'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'baXAz8wbi4Ew2vb5'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SCOPE = ['r_liteprofile', 'r_emailaddress']
SOCIAL_AUTH_LINKEDIN_OAUTH2_FIELD_SELECTORS = ['firstName', 'lastName', 'profilePicture', 'emailAddress']
SOCIAL_AUTH_LINKEDIN_OAUTH2_EXTRA_DATA = [
    ('id', 'id'),
    ('formattedName', 'name'),
    ('emailAddress', 'email_address'),
    ('pictureUrl', 'picture_url'),
    ('publicProfileUrl', 'profile_url'),
]

# http://localhost:8000/oAuth/linkedlin/

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

AUTH_USER_MODEL = 'User.User'


# EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'gator3025.hostgator.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'info@leaderterminal.com'
EMAIL_HOST_PASSWORD = 'Brady@12'

#
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.mailtrap.io'
# EMAIL_HOST_USER = '4ef87d31eedafc'
# EMAIL_HOST_PASSWORD = '20cd5dd4556920'
# EMAIL_PORT = '2525'
CSV_OUTPUT_FILE = os.path.join(BASE_DIR, 'parsed_html_csv')
CONSTANT_CONTACT_API_KEY = 'a9970027-040b-42a8-b3c1-a4250dae8d95'
CONSTANT_CONTACT_APP_TOKEN = 'F4PKkKIqkHrKG9U07cKLIg'

# STRIPE_PRIVATE_TEST_KEY = 'sk_test_51IkWytJF0XNUJISgdXtHIGFD6Y5V40fefjIgAzS4fNZKgapa7i9thXz06MkzSXt6jbU4tqhRv6ztBCyFDM96MJXe00Pkm5R24D'
# STRIPE_PUBLIC_TEST_KEY = 'pk_test_51IkWytJF0XNUJISgQBkhBZxMy6omDg9LATyYFUqOjV47TSq8bsmi1N97uO8fMjetQh2OTt29YUMDGRVDsDzOqVIk009INTBBRy'
STRIPE_PRIVATE_TEST_KEY = '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' #live keys
STRIPE_PUBLIC_TEST_KEY = 'pk_live_51IkWytJF0XNUJISg7w8ZQ57ZurMo4RXNeTBuEEa1gsETjz1f392rPcVj17wwfyvn0QsOSOMsUzlnZfjl0qQepfTu00LQmGIb7M'  # live keys

STRIPE_PRODUCT_ID = 'prod_JO4KVsHilHM2lL'
STRIPE_PRODUCT_PRICE = 'price_1IlIBvJF0XNUJISgFXenYL6Y'
STRIPE_TEST_PRODUCT_PRICE = 'price_1IkX7lJF0XNUJISgYutdSiFa'

if os.getcwd() == '/app':
    DEBUG = False
    SECURE_SSL_REDIRECT = True

django_heroku.settings(locals())

SOCIAL_AUTH_LOGIN_ERROR_URL = '/'
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'fastforward.pipeline.verify_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)


STRIPE_PUBLIC_KEY = 'pk_live_51IkWytJF0XNUJISg7w8ZQ57ZurMo4RXNeTBuEEa1gsETjz1f392rPcVj17wwfyvn0QsOSOMsUzlnZfjl0qQepfTu00LQmGIb7M'
STRIPE_SECRET_KEY = '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'
STRIPE_WEBHOOK_SECRET = 'whsec_PJMLNGZ1lzWrCXFCR8aklwGMT3XzVRre'
